export type tagLabels =
  | "JS/TS"
  | "React"
  | "mobX"
  | "Websocket"
  | "REST"
  | "GraphQL"
  | "Directus CMS"
  | "Webpack"
  | "Python"
  | "WebGL"
  | "OpenGL"
  | "Editor-UI"
  | "Unity-UI-Toolkit"
  | "ThreeJS"
  | "Geometry Shaders"
  | "Sphere projections"
  | "Kugelprojektionen"
  | "Blender"
  | "Figma"
  | "18n"
  | "Git"
  | "CSS/SASS"
  | "C++"
  | "C#"
  | "Perforce"
  | "Unity"
  | "Unreal-Engine"
  | "PS-Vita SDK"
  | "NPR"
  | "Non-photorealistic rendering"
  | "TUIO";
